name: Build

on:
  push:
    branches:
      - source

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Fetch the existing branch
      run: |
        git fetch --no-tags --prune --depth=1 origin +refs/heads/master:refs/remotes/origin/master
    - name: Set up Python
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - name: Install dependencies
      run: python -m pip install -r requirements.txt
    - name: Authenticate
      run: |
        git config --global user.name 'GitHub Actions - julian.github.io'
        git config --global user.email 'julian+githubaction@users.noreply.github.com'
        git remote set-url --push origin https://${GITHUB_ACTOR}:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: Build the site
      run: invoke build
    - name: Publish the site
      run: |
        git add output
        invoke publish
